[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "Cwpbe9jh3Ug5uBRvpoPkcHAhAQREjRysKBnXYZ6mV5Cr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/syedquasim/test/contracts/arbitrage_bot/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
tests = "anchor test"
